#!/bin/bash

set -e

#wget https://raw.github.com/openshift/openshift-extras/enterprise-1.2/enterprise/install-scripts/generic/openshift.sh
wget https://raw.github.com/calfonso/openshift-extras/enterprise-1.2/enterprise/install-scripts/generic/openshift.sh

mv openshift.sh /root/openshift.sh

cat /root/openshift.sh >> /root/openshift-mod.sh
echo "reboot" >> /root/openshift-mod.sh
